# Generated by Django 5.1.1 on 2024-11-05 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=200)),
                ('fileHash', models.CharField(default='-1', max_length=64)),
                ('uploadTime', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
