# Generated by Django 5.1.1 on 2024-11-16 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignInApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='fileHash',
        ),
    ]
