# Generated by Django 5.1.1 on 2024-10-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignInApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='username',
        ),
    ]
