# Generated by Django 5.1.1 on 2024-11-01 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignInApp', '0003_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='document',
            name='authors',
        ),
        migrations.AddField(
            model_name='document',
            name='authors',
            field=models.ManyToManyField(related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
